export function exportTXT(title: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${sanitizeFilename(title || "hiphop-rnb-forge")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportAllTXT(
  title: string,
  composition: string,
  coverResult: string,
  videoResult: string
) {
  const divider = "\n" + "═".repeat(60) + "\n";
  let text = `HIP-HOP & R&B FORGE — FULL EXPORT\nTitle: ${title || "Untitled"}\nGenerated by Hip-Hop & R&B Forge · AI Composition Suite\n`;
  text += divider;
  if (composition) {
    text += `COMPOSITION\n${"─".repeat(40)}\n${composition}\n`;
    text += divider;
  }
  if (coverResult) {
    text += `COVER ART PROMPTS\n${"─".repeat(40)}\n${coverResult}\n`;
    text += divider;
  }
  if (videoResult) {
    text += `VIDEO SCRIPT\n${"─".repeat(40)}\n${videoResult}\n`;
  }
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = buildFilename(title, composition, "-full", "txt");
  a.click();
  URL.revokeObjectURL(url);
}

export function exportCopyrightPackage(
  title: string,
  authorName: string,
  composition: string,
  style: string,
  language: string
) {
  const now = new Date();
  const timestamp = now.toISOString();
  const dateReadable = now.toLocaleDateString("en-GB", {
    day: "2-digit", month: "long", year: "numeric",
    hour: "2-digit", minute: "2-digit", second: "2-digit",
    timeZoneName: "short",
  });

  const lyricsMatch = composition.match(/\[LYRICS\]([\s\S]*?)(?=\[|$)/i);
  const lyrics = lyricsMatch ? lyricsMatch[1].trim() : "(instrumental — no lyrics)";

  const styleMatch = composition.match(/^STYLE:\s*(.+)$/im);
  const feelMatch = composition.match(/^FEEL:\s*(.+)$/im);
  const keyMatch = composition.match(/^KEY:\s*(.+)$/im);
  const formMatch = composition.match(/^FORM:\s*(.+)$/im);

  const styleValue = styleMatch ? styleMatch[1].trim() : style;
  const feelValue = feelMatch ? feelMatch[1].trim() : "—";
  const keyValue = keyMatch ? keyMatch[1].trim() : "—";
  const formValue = formMatch ? formMatch[1].trim() : "—";

  const divider = "─".repeat(60);
  const heavyDivider = "═".repeat(60);

  let text = "";

  text += `${"█".repeat(60)}\n`;
  text += `  COPYRIGHT REGISTRATION PACKAGE\n`;
  text += `  Hip-Hop & R&B Forge · AI Composition Suite\n`;
  text += `${"█".repeat(60)}\n\n`;

  text += `DOCUMENT ID:     HF-${Date.now()}\n`;
  text += `TIMESTAMP (UTC): ${timestamp}\n`;
  text += `DATE:            ${dateReadable}\n`;
  text += `\n${heavyDivider}\n\n`;

  text += `WORK IDENTIFICATION\n${divider}\n`;
  text += `Title:           ${title || "Untitled"}\n`;
  text += `Genre / Style:   ${styleValue}\n`;
  text += `Feel / Tempo:    ${feelValue}\n`;
  text += `Key:             ${keyValue}\n`;
  text += `Form:            ${formValue}\n`;
  text += `Language:        ${language}\n`;
  text += `Type of work:    Musical composition with lyrics\n`;
  text += `\n${heavyDivider}\n\n`;

  text += `AUTHORSHIP\n${divider}\n`;
  text += `Author / Composer:  ${authorName || "Author not specified"}\n`;
  text += `Role:               Composer, Lyricist, Arranger\n`;
  text += `Authorship share:   100%\n`;
  text += `Creation tool:      Hip-Hop & R&B Forge AI Composition Suite\n`;
  text += `\nNote: This document certifies the date and content of the creative\n`;
  text += `work at the time of generation. The author is responsible for\n`;
  text += `registration with the relevant performing rights organization\n`;
  text += `(GEMA, ASCAP, BMI, PRS, SACEM, RAO, etc.).\n`;
  text += `\n${heavyDivider}\n\n`;

  text += `LYRICS\n${divider}\n`;
  text += `${lyrics}\n`;
  text += `\n${heavyDivider}\n\n`;

  text += `FULL COMPOSITION\n${divider}\n`;
  text += `${composition}\n`;
  text += `\n${heavyDivider}\n\n`;

  text += `GEMA REGISTRATION FIELDS (for manual submission)\n${divider}\n`;
  text += `Title of work:          ${title || "Untitled"}\n`;
  text += `Original title:         ${title || "Untitled"}\n`;
  text += `Type:                   Original work\n`;
  text += `Genre:                  ${styleValue}\n`;
  text += `Duration (estimated):   3:30\n`;
  text += `Language of lyrics:     ${language}\n`;
  text += `Composer:               ${authorName || "—"} · share: 50%\n`;
  text += `Lyricist:               ${authorName || "—"} · share: 50%\n`;
  text += `Publisher:              (fill in if applicable)\n`;
  text += `ISRC:                   (assign after recording)\n`;
  text += `ISWC:                   (assigned by GEMA/CISAC after registration)\n`;
  text += `\n${heavyDivider}\n\n`;

  text += `DECLARATION\n${divider}\n`;
  text += `I, ${authorName || "[Author Name]"}, declare that:\n`;
  text += `\n`;
  text += `1. I am the sole author and rights holder of the work described above.\n`;
  text += `2. This work was created on ${dateReadable}.\n`;
  text += `3. The content of this document accurately reflects the work\n`;
  text += `   as it existed at the time of creation.\n`;
  text += `4. I have not assigned or licensed these rights to any third party\n`;
  text += `   without explicit written agreement.\n`;
  text += `\n`;
  text += `Signature: _______________________________\n`;
  text += `Date:      _______________________________\n`;
  text += `\n${heavyDivider}\n\n`;

  text += `Generated by Hip-Hop & R&B Forge · AI Composition Suite\n`;
  text += `Document ID: HF-${Date.now()} · ${timestamp}\n`;

  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${sanitizeFilename(title || "hiphop-rnb-forge")}-copyright.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

function buildFilename(title: string, composition: string, suffix: string, ext: string): string {
  const raw = title ||
    composition.split("\n").find(l => /^#?\s*TITLE:/i.test(l))?.replace(/^#?\s*TITLE:/i, "").trim() ||
    "hiphop-rnb-forge";
  const slug = raw
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim()
    .slice(0, 80) || "hiphop-rnb-forge";
  return `${slug}${suffix}.${ext}`;
}

function sanitizeFilename(value: string): string {
  return value
    .replace(/[<>:"/\\|?*\u0000-\u001F]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 120) || "hiphop-rnb-forge";
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function preserveInlineFormatting(value: string): string {
  return escapeHtml(value)
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>");
}

function formatContent(content: string): string {
  return content
    .split("\n")
    .map((line) => {
      const trimmed = line.trim();

      if (!trimmed || trimmed === "---" || trimmed === "***") {
        return `<div style="height:6px"></div>`;
      }

      if (/^\[.+\]$/.test(trimmed)) {
        return `<div style="font-size:9px;font-weight:600;color:#A855F7;letter-spacing:0.12em;text-transform:uppercase;margin-top:16px;margin-bottom:6px;padding-bottom:4px;border-bottom:1px solid #242428;">${preserveInlineFormatting(
          trimmed.replace(/^\[/, "").replace(/\]$/, "")
        )}</div>`;
      }

      if (/^(TITLE|STYLE|FEEL|KEY|FORM|MOOD|TEMPO|LANGUAGE|MODE|INSTRUMENTS|THEME):/i.test(trimmed)) {
        return `<div style="font-family:'Courier New',monospace;font-size:9px;color:#8A8578;line-height:1.6;margin-bottom:3px;white-space:pre-wrap;">${preserveInlineFormatting(
          trimmed
        )}</div>`;
      }

      if (/^(SECTION\s+[A-Z0-9-]+\s*-|SECTION\s+[A-Z0-9-]+$)/i.test(trimmed)) {
        return `<div style="font-size:11px;font-weight:700;color:#F0EDE6;margin-top:14px;margin-bottom:4px;letter-spacing:0.04em;">${preserveInlineFormatting(
          trimmed
        )}</div>`;
      }

      if (/^(Composition|Lyrics|Arrangement)$/i.test(trimmed)) {
        return `<div style="font-size:14px;font-weight:700;color:#F0EDE6;margin-top:18px;margin-bottom:8px;letter-spacing:0.03em;">${preserveInlineFormatting(
          trimmed
        )}</div>`;
      }

      if (/^RefineCopy$/i.test(trimmed)) {
        return `<div style="font-size:9px;color:#4A4840;letter-spacing:0.08em;text-transform:uppercase;margin-bottom:8px;">${preserveInlineFormatting(
          trimmed
        )}</div>`;
      }

      if (/^(Riff|Drums|Melody|Hook|Build|Atmosphere|Direction|Notes|Arrangement lift|Tension device):/i.test(trimmed)) {
        return `<div style="font-size:10px;font-weight:600;color:#C084FC;margin-top:10px;margin-bottom:3px;">${preserveInlineFormatting(
          trimmed
        )}</div>`;
      }

      if (trimmed.startsWith("#")) {
        return `<div style="font-size:12px;font-weight:700;color:#F0EDE6;margin-top:10px;margin-bottom:4px;">${preserveInlineFormatting(
          trimmed.replace(/^#+\s*/, "")
        )}</div>`;
      }

      return `<div style="font-size:10px;color:#D6D1C7;line-height:1.72;margin-bottom:2px;white-space:pre-wrap;">${preserveInlineFormatting(
        trimmed.replace(/^[-*]\s/, "")
      )}</div>`;
    })
    .join("\n");
}

function sectionDivider(label: string): string {
  return `
    <div style="
      margin: 40px 0 24px;
      padding: 16px 0 14px;
      border-top: 2px solid #A855F7;
      border-bottom: 1px solid #242428;
      display: flex;
      align-items: center;
      gap: 12px;
    ">
      <div style="
        font-size: 10px;
        font-weight: 700;
        color: #A855F7;
        letter-spacing: 0.2em;
        text-transform: uppercase;
      ">${escapeHtml(label)}</div>
      <div style="flex:1;height:1px;background:#242428;"></div>
    </div>
  `;
}

async function loadPdfLibs() {
  const [{ jsPDF }, html2canvasModule] = await Promise.all([
    import("jspdf"),
    import("html2canvas"),
  ]);
  return { jsPDF, html2canvas: html2canvasModule.default };
}

async function renderToPDF(title: string, htmlContent: string, filename: string): Promise<void> {
  const { jsPDF, html2canvas } = await loadPdfLibs();

  const container = document.createElement("div");
  container.style.cssText = `
    position: fixed;
    left: -10000px;
    top: 0;
    width: 794px;
    background: #0D0D0F;
    color: #F0EDE6;
    font-family: Arial, sans-serif;
    font-size: 11px;
    line-height: 1.6;
    padding: 48px;
    box-sizing: border-box;
    z-index: -1;
  `;

  container.innerHTML = `
    <div style="font-size:24px;font-weight:700;color:#A855F7;margin-bottom:4px;">
      ${escapeHtml(title || "Untitled")}
    </div>
    <div style="font-size:9px;color:#4A4840;letter-spacing:0.08em;margin-bottom:20px;padding-bottom:12px;border-bottom:1px solid #A855F7;">
      Generated by Hip-Hop & R&B Forge · AI Composition Suite
    </div>
    ${htmlContent}
    <div style="margin-top:40px;padding-top:12px;border-top:1px solid #242428;font-size:8px;color:#4A4840;letter-spacing:0.06em;">
      Exported from Hip-Hop & R&B Forge
    </div>
  `;

  document.body.appendChild(container);

  try {
    await new Promise((resolve) => requestAnimationFrame(() => resolve(null)));

    const canvas = await html2canvas(container, {
      scale: 2,
      backgroundColor: "#0D0D0F",
      useCORS: true,
      logging: false,
      height: container.scrollHeight,
      windowHeight: container.scrollHeight,
      width: container.scrollWidth,
      scrollX: 0,
      scrollY: 0,
    });

    const pdf = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4", compress: true });

    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    const margin = 24;
    const renderWidth = pdfWidth - margin * 2;
    const renderHeight = pdfHeight - margin * 2;
    const ratio = renderWidth / canvas.width;
    const fullHeight = canvas.height * ratio;

    let remaining = fullHeight;
    let sourceY = 0;
    const pageHeightInCanvas = renderHeight / ratio;
    let firstPage = true;

    while (remaining > 0) {
      if (!firstPage) pdf.addPage();
      firstPage = false;

      const pageCanvas = document.createElement("canvas");
      pageCanvas.width = canvas.width;
      pageCanvas.height = Math.min(pageHeightInCanvas, canvas.height - sourceY);

      const pageCtx = pageCanvas.getContext("2d");
      if (!pageCtx) throw new Error("Canvas context unavailable");

      pageCtx.drawImage(canvas, 0, sourceY, canvas.width, pageCanvas.height, 0, 0, canvas.width, pageCanvas.height);

      const pageHeight = pageCanvas.height * ratio;
      pdf.setFillColor(13, 13, 15);
      pdf.rect(0, 0, pdfWidth, pdfHeight, "F");
      pdf.addImage(pageCanvas.toDataURL("image/png"), "PNG", margin, margin, renderWidth, pageHeight);

      remaining -= renderHeight;
      sourceY += pageHeightInCanvas;
    }

    const pdfBlob = pdf.output("blob");
    const pdfUrl = URL.createObjectURL(pdfBlob);
    const pdfLink = document.createElement("a");
    pdfLink.href = pdfUrl;
    pdfLink.download = filename;
    pdfLink.style.display = "none";
    document.body.appendChild(pdfLink);
    pdfLink.click();
    document.body.removeChild(pdfLink);
    setTimeout(() => URL.revokeObjectURL(pdfUrl), 150);
  } catch (error) {
    console.error(error);
    alert("PDF export failed.");
  } finally {
    document.body.removeChild(container);
  }
}

export async function exportPDF(title: string, content: string): Promise<void> {
  const html = formatContent(content);
  await renderToPDF(title, html, `${sanitizeFilename(title || "hiphop-rnb-forge")}.pdf`);
}

export async function exportAllPDF(
  title: string,
  composition: string,
  coverResult: string,
  videoResult: string
): Promise<void> {
  const parts: string[] = [];
  if (composition) { parts.push(sectionDivider("Composition")); parts.push(formatContent(composition)); }
  if (coverResult) { parts.push(sectionDivider("Cover Art Prompts")); parts.push(formatContent(coverResult)); }
  if (videoResult) { parts.push(sectionDivider("Video Script")); parts.push(formatContent(videoResult)); }
  if (parts.length === 0) { alert("Nothing to export."); return; }
  await renderToPDF(title || "Untitled", parts.join("\n"), buildFilename(title, composition, "-full", "pdf"));
}
